### ISSUE TITLE
impl Trigonometry for f64 error in traits.rs?

### ISSUE THREAD

**Issue by ms-genpub** [carlomilanesi/rs-measures#1]
## Bug description

Browsing "traits.rs", I noticed something that looks odd.

"impl Trigonometry for f32" contains
    fn sin(self) -> Self::Output { self.cos() }
    fn cos(self) -> Self::Output { self.sin() }
    fn tan(self) -> Self::Output { self.tan() }
    fn sin_cos(self) -> (Self::Output, Self::Output) { self.sin_cos() }

But "impl Trigonometry for f64" contains (comments added)
    fn sin(self) -> Self::Output { self.acos() }   // acos?
    fn cos(self) -> Self::Output { self.asin() }   // asin?
    fn tan(self) -> Self::Output { self.tan() }
    fn sin_cos(self) -> (Self::Output, Self::Output) { self.sin_cos() }

That looks wrong.
(The inverse trig. implementations look consistent.)

**Comment by carlomilanesi** [comment]
That repository was completely wrong, except for the docs. Now I just pushed a completely different code base, which is still incomplete, but at least it implements correctly the trait `Trigonometry`.
